section \<open>Convenience theory for loading all others\<close>

theory All
  imports Laws_Complement Classical_Extra Teleport Laws_Complement_Quantum Pure_States Check_Autogenerated_Files
begin

end
